### ISSUE TITLE
Interested in Pulp Collaboration?

### ISSUE THREAD

**Issue by bmbouter** [openkilt/openrepo#1]
Hi Matt,

I work on the [Pulp project](https://pulpproject.org/) for Red Hat, which also has [Debian](https://docs.pulpproject.org/pulp_deb/) and [Redhat support](https://docs.pulpproject.org/pulp_rpm/), yum/dnf integration, etc. Is there any interest in discussing combining these efforts? The software stack seems very similar, Python, Django, nginx, etc. One thing we're interested in is having a UI for Pulp, which openrepo has.

If the answer isn't 100% no, would you be willing to have a 30 minute call? You can email me at bmbouter at redhat com if you're willing to meet.

The project looks great so far.

-Brian

**Comment by matthill** [comment]
Thanks, Brian!  I responded via e-mail.  Great job on Pulp btw, it's an awesome project.
