### ISSUE TITLE
curl on signed key for a repo as per repo instructions results in a 404 Not Found. 

### ISSUE THREAD

**Issue by radhaksri** [openkilt/openrepo#22]
Steps to reproduce:

1. Launch openrepo as per https://github.com/openkilt/openrepo#getting-started:

```
wget https://raw.githubusercontent.com/openkilt/openrepo/master/docker-compose.yml`
docker compose up -d
```

2. Open the web ui, create a signed key, login with admin/ admin, setup a repository and associate the repo with the signed key. 
3. From the repo instructions, try this curl command

`curl http://127.0.0.1:7376/test-repo/public.gpg`

4. The curl command results in a 404 Not Found.

**Comment by radhaksri** [comment]
@matthill , @denisgolius,  @k0ste , @inistor : Any pointers about how I can fix / workaround this?

**Comment by inistor** [comment]
If you access https://127.0.0.1:7376/cfg/repo/test-repo from a browser, do you get the GUI? 
Could you please post the docker logs for all containers?
`docker compose logs > allcontainers.log` from the folder containing `docker-compose.yaml`

**Comment by radhaksri** [comment]
Repeated the exercise and collected logs/ screenshots:

[all_containers_launch.log](https://github.com/user-attachments/files/16588200/all_containers_launch.log)
[all_containers_test.log](https://github.com/user-attachments/files/16588201/all_containers_test.log)

all_containers_launch.log : logs right after a clean docker compose up -d. No login, no test repo/ signing key created.
all_containers_test.log: logs collected after logging in with admin/ admin, creating a test signingkey, creating a repo and trying to do a curl. 

Screenshots:

![Screenshot 2024-08-12 092253](https://github.com/user-attachments/assets/4ed2774a-6ba0-4cc6-9da0-abeb038ce648)
![Screenshot 2024-08-12 092308](https://github.com/user-attachments/assets/a132c28d-8b07-42b8-9c5d-67c9fb251a67)
![Screenshot 2024-08-12 092424](https://github.com/user-attachments/assets/3cab1c1e-0724-496f-8c95-a16201ec677b)
![Screenshot 2024-08-12 092439](https://github.com/user-attachments/assets/7bdfa177-1a61-4404-9bce-ea70bd6dc465)

p.s: 192.168.56.102 is the IP address of my dev VM.

**Comment by inistor** [comment]
There's a problem with your DB container, apparently:

From the init log:
```
django-1  | psycopg2.OperationalError: connection to server at "db" (172.18.0.2), port 5432 failed: Connection refused
django-1  | 	Is the server running on that host and accepting TCP/IP connections?
```

From the launch log:
```
db-1      | initdb: warning: enabling "trust" authentication for local connections
django-1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django-1  | psycopg2.OperationalError: connection to server at "db" (172.18.0.2), port 5432 failed: Connection refused
django-1  | 	Is the server running on that host and accepting TCP/IP connections?
```

In the `docker-compose.yaml`, there's a [DB container](https://github.com/openkilt/openrepo/blob/714883c2f6e5b5d300310ab6197a75a0e1aa6405/docker-compose.yml#L50) which should be running. For some reason, it's not running (or it's not accessible by the other containers).

I still don't understand how you were able to access the GUI - the logs you sent pretty much only include  DB errors

**Comment by inistor** [comment]
Actually, I might be wrong and that's before the DB starts; however, I don't see the logs of the `nginx` container

**Comment by inistor** [comment]
If you can acces the GUI, please check the build status.
Click on the link with the icon:  <img width="56" alt="image" src="https://github.com/user-attachments/assets/53c7002b-dd5b-490a-a3c3-8942ac98be8f">

The worker container should be generating the repository structure in the required form, based what you created in the GUI; from there, the `nginx` container should serve it directly; you can clearly reach the `nginx` container, however the repository structure is not generated; also, have you uploaded any packages?

**Comment by radhaksri** [comment]
Noticed those errors in django container - I think the django container was trying to do operations much before the db container is up and running. I think the db container should have a healthcheck that establishes that the db is up and running, which the django container can rely upon properly. Something like this - https://github.com/peter-evans/docker-compose-healthcheck - maybe?

> There's a problem with your DB container, apparently:
> 
> From the init log:
> 
> ```
> django-1  | psycopg2.OperationalError: connection to server at "db" (172.18.0.2), port 5432 failed: Connection refused
> django-1  | 	Is the server running on that host and accepting TCP/IP connections?
> ```
> 
> From the launch log:
> 
> ```
> db-1      | initdb: warning: enabling "trust" authentication for local connections
> django-1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> django-1  | psycopg2.OperationalError: connection to server at "db" (172.18.0.2), port 5432 failed: Connection refused
> django-1  | 	Is the server running on that host and accepting TCP/IP connections?
> ```
> 
> In the `docker-compose.yaml`, there's a [DB container](https://github.com/openkilt/openrepo/blob/714883c2f6e5b5d300310ab6197a75a0e1aa6405/docker-compose.yml#L50) which should be running. For some reason, it's not running (or it's not accessible by the other containers).
> 
> I still don't understand how you were able to access the GUI - the logs you sent pretty much only include DB errors

**Comment by radhaksri** [comment]
No, I do not have any packages uploaded at the moment. Will try the same after doing so, and report what I see. 

> If you can acces the GUI, please check the build status. Click on the link with the icon: <img alt="image" width="56" src="https://private-user-images.githubusercontent.com/13348711/357110682-53c7002b-dd5b-490a-a3c3-8942ac98be8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NzcyODEsIm5iZiI6MTcyMzQ3Njk4MSwicGF0aCI6Ii8xMzM0ODcxMS8zNTcxMTA2ODItNTNjNzAwMmItZGQ1Yi00OTBhLWEzYzMtODk0MmFjOThiZThmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDE1MzYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2M2IzNWQ4OGVhYmZkNWYwM2Q4MTQ2MjcwMTI1NzIyNDZkMGU1NGVmNDYwM2QxOWEyYjM4OTI2ZTdlYjFlNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kwWXYaRz5hfj7U6gVPBiG6ivz0yGMGHeHDkuP3XZLTU">
> 
> The worker container should be generating the repository structure in the required form, based what you created in the GUI; from there, the `nginx` container should serve it directly; you can clearly reach the `nginx` container, however the repository structure is not generated; also, have you uploaded any packages?

**Comment by radhaksri** [comment]
I think uploading a package fixed it. I see statements in the build output that is writing the gpg key to the directory. 

Screenshots of the build log:

![Screenshot 2024-08-12 104301](https://github.com/user-attachments/assets/02d52383-8e48-4a9d-bda0-48cb5c0f1278)
![Screenshot 2024-08-12 104316](https://github.com/user-attachments/assets/a9e1241d-d18f-4e51-bf82-2545d5b19254)

**Comment by inistor** [comment]
Great. Sorry for the confusion with the DB connection, I was mislead by the logs.

**Comment by radhaksri** [comment]
Thanks for the help here, @inistor !

**Comment by radhaksri** [comment]
Created a PR #23 to address this issue. 

> Noticed those errors in django container - I think the django container was trying to do operations much before the db container is up and running. I think the db container should have a healthcheck that establishes that the db is up and running, which the django container can rely upon properly. Something like this - https://github.com/peter-evans/docker-compose-healthcheck - maybe?
> 
> > There's a problem with your DB container, apparently:
> > From the init log:
> > ```
> > django-1  | psycopg2.OperationalError: connection to server at "db" (172.18.0.2), port 5432 failed: Connection refused
> > django-1  | 	Is the server running on that host and accepting TCP/IP connections?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > From the launch log:
> > ```
> > db-1      | initdb: warning: enabling "trust" authentication for local connections
> > django-1  |     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
> > django-1  | psycopg2.OperationalError: connection to server at "db" (172.18.0.2), port 5432 failed: Connection refused
> > django-1  | 	Is the server running on that host and accepting TCP/IP connections?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In the `docker-compose.yaml`, there's a [DB container](https://github.com/openkilt/openrepo/blob/714883c2f6e5b5d300310ab6197a75a0e1aa6405/docker-compose.yml#L50) which should be running. For some reason, it's not running (or it's not accessible by the other containers).
> > I still don't understand how you were able to access the GUI - the logs you sent pretty much only include DB errors

**Comment by radhaksri** [comment]
Created an enhancement request: #24 to track this. Will close this issue here.  

> A question though: Shouldn't the gpg key be accessible irrespective of the repo being empty? A probable enhancement?
