### ISSUE TITLE
CLI unable to upload new package

### ISSUE THREAD

**Issue by populationless** [openkilt/openrepo#8]
Hi Matt,

I'm trying to upload a new package to my openrepo via CLI like so:

`openrepo_cli_x86_64 -k <KEY> -s https://openrepo.my-doman.com upload -r repo package.deb`

That yields the following error:

```
Error.  Received response code 400
{"detail":"Error processing uploaded file"}
```

The logs from openrepo-django-1 show:
`WARNING log:241: Bad Request: /api/repo/upload/`

This has worked in the past. I think it stopped working around March-ish. I have already tried the 'new' [openrepo_cli_x86_64 from March 6](https://github.com/openkilt/openrepo/releases/tag/v1.0.0), same behavior. All containers are up-to-date.

Any idea what is going on?

**Comment by matthill** [comment]
Do other package uploads work?  If so, can you upload the current deb/rpm and the one that is replacing it?

**Comment by populationless** [comment]
I'm terribly sorry, I have done goofed. I had a script download the latest .deb from a Github project, and my script had an error and downloaded gibberish instead. Everything works as intended, my bad. 😰

**Comment by matthill** [comment]
No worries.  The fact that it wasn't obvious what the problem was may mean we need some error message or logging.
